### ISSUE TITLE
Utiliser la structure de données bitset (économiser la taille des données)

### ISSUE THREAD

**Issue by Arteox** [Noomaok/mini_aevol#2]

**Comment by Noomaok** [comment]
La structure de la std bitset ne peut pas avoir une taille défini pendant le runtime.
On explore alors la possibilité d'utiliser [dynamic_bitset](https://www.boost.org/doc/libs/1_75_0/libs/dynamic_bitset/dynamic_bitset.html) de la library boost pour contourner cette limitation.

**Comment by Noomaok** [comment]
Changement de la structure de donnée de l'adn. On utilise désormais la structure dynamic_bitset pour remplacer le vecteur de caractère. Sur deux runs similaire, on perd un peux de temps d'exécution mais on gagne environ 1/3 d'espace mémoire (Test réalisé avec valgrind). 
La branche `from_vector_to_bitset`  a été merge dans la branche `optimized` #9
